# Generated by Django 5.0.2 on 2024-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_post_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
    ]
