# Generated by Django 5.0.2 on 2024-03-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_post_allow_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='allow_comment',
            new_name='on_comment',
        ),
    ]
