# Generated by Django 5.0.2 on 2024-03-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_reactionpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reactionpost',
            unique_together={('user', 'post')},
        ),
    ]
